name: Build binaries

on:
  push:
    tags:
      - 'v*.*.*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

    - name: Install packages
      run: |
        sudo apt install gcc-arm-none-eabi
        git submodule init
        git submodule update

    - name: Configure CMake
      run: |
        mkdir ./build
        cd ./build
        cmake -G"Unix Makefiles" ..

    - name: Build
      run: |
        cd ./build
        cmake --build .
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}-${{ steps.vars.outputs.sha_short }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
    - name: Upload STMCMAKE artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/STMCMAKE.bin
        asset_name: STMCMAKE.bin
        asset_content_type: application/octet-stream
      
