name: Build binaries

on:
  push:
    tags:
      - 'v*.*.*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install packages
      run: |
        sudo apt install gcc-arm-none-eabi
        git submodule init
        git submodule update

    - name: Configure CMake
      run: |
        mkdir ./build
        cd ./build
        cmake -G"Unix Makefiles" ..

    - name: Build
      run: |
        cd ./build
        cmake --build .
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: "${{ github.ref }}-${{ env.GITHUB_SHA }}"
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    - name: Upload STMCMAKE artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/STMCMAKE.bin
        asset_name: STMCMAKE.bin
        asset_content_type: application/octet-stream
      
