name: Build binaries

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install packages
      run: |
        sudo apt install gcc-arm-none-eabi
        git submodule init
        git submodule update

    - name: Configure CMake
      run: |
        mkdir ./build
        cd ./build
        cmake -G"Unix Makefiles" ..

    - name: Build
      run: |
        cd ./build
        cmake --build .
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: "Build ${{ env.GITHUB_SHA }}"
        tag_name: "${{ env.GITHUB_SHA }}"
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
